name: 'Node to GH'
description: 'Build & Deploy a Node.js app to Github Pages'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ./node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
      shell: bash
    - run: npm run build
      shell: bash
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
